name = "auth"
main = "src/worker.js"
compatibility_date = "2024-12-13"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "workers.tablerus.es/auth/*"
zone_name = "tablerus.es"

[placement]
mode = "smart"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true

[[kv_namespaces]]
id = "efe5fd2d2d014e9b9fd6867bed2372d4"
binding = "AUTH_SESSIONS"

[[kv_namespaces]]
id = "38150bc6010548a68df61c9503e1aba2"
binding = "AUTH_USERS"

[[services]]
binding = "UTILS"
service = "utils"
environment = "production"
entrypoint = "UtilsWorker"
